# Generated by Django 3.0.7 on 2020-10-14 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_careervacancy_displayuserreviews_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careervacancy',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='careervacancy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='career_vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.CareerVacancy'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
