# Generated by Django 3.0.7 on 2020-10-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201014_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayuserreviews',
            name='designation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
