# Generated by Django 3.0.7 on 2020-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_image',
            field=models.ImageField(upload_to='media_images'),
        ),
    ]
