# Generated by Django 3.0.7 on 2020-10-22 12:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_add_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editabletext',
            name='key',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='editabletext',
            name='value',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
