# Generated by Django 3.0.7 on 2020-11-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20201022_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website_pictures')),
                ('key', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
