# Generated by Django 3.0.7 on 2020-09-23 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('tests', models.ManyToManyField(to='appointments.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'pending'), ('paid', 'paid'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('done', 'done')], default='pending', max_length=100, no_check_for_status=True)),
                ('appointment_date', models.DateField()),
                ('total_price', models.FloatField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('panels', models.ManyToManyField(to='appointments.Panel')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.TimeSlot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
