# Generated by Django 3.0.7 on 2020-08-25 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20200825_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='timeslot_timestamp',
            new_name='end_timestamp',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
