# Generated by Django 3.0.7 on 2020-08-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20200825_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_removed',
        ),
    ]
