# Generated by Django 3.0.7 on 2020-10-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alias_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
