# Generated by Django 3.0.7 on 2020-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20201011_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_taken',
        ),
        migrations.AddField(
            model_name='category',
            name='price_type',
            field=models.CharField(choices=[('CONVENTIONAL', 'CONVENTIONAL'), ('RANGE', 'RANGE')], default='CONVENTIONAL', max_length=16),
        ),
        migrations.AddField(
            model_name='category',
            name='secondary_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='appointment_count',
            field=models.IntegerField(default=0),
        ),
    ]
