# Generated by Django 3.0.7 on 2020-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20201016_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='interval_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='interval_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='start_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
