# Generated by Django 3.0.7 on 2020-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20201021_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
