# Generated by Django 3.0.7 on 2020-10-22 12:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_category_is_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
